# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: httpspamscorer 0.1.0 ruby lib

Gem::Specification.new do |s|
  s.name = "httpspamscorer"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Jakub Pastuszek"]
  s.date = "2014-10-03"
  s.description = "It takes parsed e-mail headers, text and html body and reconstructs it into e-mail message that then is provided to RSpmad backed for checking or learning."
  s.email = "jpastuszek@gmail.com"
  s.executables = ["httpspamscorer"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/httpspamscorer",
    "features/step_definitions/httpspamscorer_steps.rb",
    "features/support/env.rb",
    "lib/httpspamscorer.rb",
    "lib/httpspamscorer/error_reporter.rb",
    "lib/httpspamscorer/reconstructed_mail.rb",
    "spec/features/api_error_handling_spec.rb",
    "spec/features/checking_api_spec.rb",
    "spec/features/learning_api_spec.rb",
    "spec/features/rspamd_protocol_spec.rb",
    "spec/features/stat_api_spec.rb",
    "spec/reconstructed_mail_spec.rb",
    "spec/spec_helper.rb",
    "spec/support/ham.eml",
    "spec/support/image.png",
    "spec/support/rspamd",
    "spec/support/rspamd-legacy.conf",
    "spec/support/rspamd.conf.d/modules.conf",
    "spec/support/rspamd.conf.d/rspamd.conf",
    "spec/support/spam.eml"
  ]
  s.homepage = "http://github.com/jpastuszek/httpspamscorer"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.2"
  s.summary = "Sends reconstructed e-mail to RSpamd backend for checking and learning."

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<unicorn-cuba-base>, ["~> 1.3"])
      s.add_runtime_dependency(%q<mail>, ["~> 2.6.1"])
      s.add_runtime_dependency(%q<excon>, [">= 0.39"])
      s.add_development_dependency(%q<rspec>, ["~> 3.1"])
      s.add_development_dependency(%q<rspec-its>, ["~> 1.0.1"])
      s.add_development_dependency(%q<cucumber>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<rspec-background-process>, ["~> 0.1"])
    else
      s.add_dependency(%q<unicorn-cuba-base>, ["~> 1.3"])
      s.add_dependency(%q<mail>, ["~> 2.6.1"])
      s.add_dependency(%q<excon>, [">= 0.39"])
      s.add_dependency(%q<rspec>, ["~> 3.1"])
      s.add_dependency(%q<rspec-its>, ["~> 1.0.1"])
      s.add_dependency(%q<cucumber>, [">= 0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<rspec-background-process>, ["~> 0.1"])
    end
  else
    s.add_dependency(%q<unicorn-cuba-base>, ["~> 1.3"])
    s.add_dependency(%q<mail>, ["~> 2.6.1"])
    s.add_dependency(%q<excon>, [">= 0.39"])
    s.add_dependency(%q<rspec>, ["~> 3.1"])
    s.add_dependency(%q<rspec-its>, ["~> 1.0.1"])
    s.add_dependency(%q<cucumber>, [">= 0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<rspec-background-process>, ["~> 0.1"])
  end
end

